Repository 4team-tuna/be14-2nd-tuna-GoMen, pull requests merged in 2025-03, with the labels that each got.

#5 [UPDATE] Member 패지키명 User로 변경
  gomen/src/main/java/com/tuna/gomen/User/dummy.java
  gomen/src/main/java/com/tuna/gomen/mapper/MentoringMapper.java
  gomen/src/main/java/com/tuna/gomen/member/dummy.java
  gomen/src/main/java/com/tuna/gomen/mentoring/MentoringService.java
  gomen/src/main/resources/mapper/MentoringMapper.xml
Labels: refactor

#6 test
  gomen/src/main/java/com/tuna/gomen/GomenApplication.java
  gomen/src/main/java/com/tuna/gomen/board/controller/BoardController.java
  gomen/src/main/java/com/tuna/gomen/board/domain/entity/BoardEntity.java
  gomen/src/main/java/com/tuna/gomen/board/dto/BoardDto.java
  gomen/src/main/java/com/tuna/gomen/board/service/BoardService.java
  gomen/src/main/java/com/tuna/gomen/bookMarkandLike/controller/BookmarkController.java
  gomen/src/main/java/com/tuna/gomen/bookMarkandLike/domain/entity/BookmarkEntity.java
  gomen/src/main/java/com/tuna/gomen/bookMarkandLike/dto/BookmarkedBoardDto.java
  gomen/src/main/java/com/tuna/gomen/bookMarkandLike/service/BookmarkService.java
  gomen/src/main/java/com/tuna/gomen/mapper/BoardMapper.java
  gomen/src/main/java/com/tuna/gomen/mapper/BookmarkMapper.java
  gomen/src/main/java/com/tuna/gomen/mapper/ReportMapper.java
  gomen/src/main/java/com/tuna/gomen/report/ReportService.java
  gomen/src/main/resources/mapper/BoardMapper.xml
  gomen/src/main/resources/mapper/BookmarkMapper.xml
  gomen/src/main/resources/mapper/ReportMapper.xml
Labels: 🐣enhancement

#8 feature/board/ 사용자,카테고리,제목 키워드별 조회 기능 구현
  Tuna-Back-end-project/HELP.md
  Tuna-Back-end-project/build.gradle
  Tuna-Back-end-project/build/classes/java/main/com/tuna/gomen/TunaBackEndProjectApplication.class
  Tuna-Back-end-project/build/classes/java/main/com/tuna/gomen/config/MyBatisConfig.class
  Tuna-Back-end-project/build/classes/java/main/com/tuna/gomen/controller/MemberController.class
  Tuna-Back-end-project/build/classes/java/main/com/tuna/gomen/entity/Member.class
  Tuna-Back-end-project/build/classes/java/main/com/tuna/gomen/mapper/MemberMapper.class
  Tuna-Back-end-project/build/classes/java/main/com/tuna/gomen/model/Member.class
  Tuna-Back-end-project/build/classes/java/main/com/tuna/gomen/service/MemberService.class
  Tuna-Back-end-project/build/reports/problems/problems-report.html
  Tuna-Back-end-project/build/resources/main/application.yml
  Tuna-Back-end-project/build/resources/main/mappers/MemberMapper.xml
  Tuna-Back-end-project/build/tmp/compileJava/compileTransaction/stash-dir/Member.class.uniqueId5
  Tuna-Back-end-project/build/tmp/compileJava/compileTransaction/stash-dir/Member.class.uniqueId6
  Tuna-Back-end-project/build/tmp/compileJava/compileTransaction/stash-dir/MemberController.class.uniqueId1
  Tuna-Back-end-project/build/tmp/compileJava/compileTransaction/stash-dir/MemberMapper.class.uniqueId2
  Tuna-Back-end-project/build/tmp/compileJava/compileTransaction/stash-dir/MemberService.class.uniqueId3
  Tuna-Back-end-project/build/tmp/compileJava/compileTransaction/stash-dir/MyBatisConfig.class.uniqueId4
  Tuna-Back-end-project/build/tmp/compileJava/compileTransaction/stash-dir/TunaBackEndProjectApplication.class.uniqueId0
  Tuna-Back-end-project/build/tmp/compileJava/previous-compilation-data.bin
  Tuna-Back-end-project/gradle/wrapper/gradle-wrapper.jar
  Tuna-Back-end-project/gradle/wrapper/gradle-wrapper.properties
  Tuna-Back-end-project/gradlew
  Tuna-Back-end-project/gradlew.bat
  Tuna-Back-end-project/settings.gradle
  Tuna-Back-end-project/src/main/java/com/ohgiraffers/tuna/TunaBackEndProjectApplication.java
  Tuna-Back-end-project/src/main/java/com/ohgiraffers/tuna/config/MyBatisConfig.java
  Tuna-Back-end-project/src/main/java/com/ohgiraffers/tuna/controller/MemberController.java
  Tuna-Back-end-project/src/main/java/com/ohgiraffers/tuna/entity/Member.java
  Tuna-Back-end-project/src/main/java/com/ohgiraffers/tuna/mapper/MemberMapper.java
  Tuna-Back-end-project/src/main/java/com/ohgiraffers/tuna/model/Member.java
  Tuna-Back-end-project/src/main/java/com/ohgiraffers/tuna/service/MemberService.java
  Tuna-Back-end-project/src/main/resources/application.yml
  Tuna-Back-end-project/src/main/resources/mappers/MemberMapper.xml
  Tuna-Back-end-project/src/test/java/com/ohgiraffers/tuna/MemberMapperTest.java
  Tuna-Back-end-project/src/test/java/com/ohgiraffers/tuna/TunaBackEndProjectApplicationTests.java
  gomen/src/main/java/com/tuna/gomen/board/controller/BoardController.java
  gomen/src/main/java/com/tuna/gomen/board/domain/entity/CommentEntity.java
  gomen/src/main/java/com/tuna/gomen/board/domain/entity/UserEntity.java
  gomen/src/main/java/com/tuna/gomen/board/dto/CommentDto.java
  gomen/src/main/java/com/tuna/gomen/board/dto/UserDto.java
  gomen/src/main/java/com/tuna/gomen/board/service/BoardService.java
  gomen/src/main/java/com/tuna/gomen/mapper/BoardMapper.java
  gomen/src/main/java/com/tuna/gomen/mapper/dummy.java
  gomen/src/main/java/com/tuna/gomen/report/Report.java
  gomen/src/main/java/com/tuna/gomen/report/ReportController.java
  gomen/src/main/resources/mapper/BoardMapper.xml
Labels: 🐣enhancement

#43 Update DummyData_New.sql
  DummyData_New.sql
Labels: Database-fix

#49 [MENTORING] 조회 기능 구현 완료
  gomen/src/main/java/com/tuna/gomen/mapper/MentorListMapper.java
  gomen/src/main/java/com/tuna/gomen/mapper/MentoringBoardMapper.java
  gomen/src/main/java/com/tuna/gomen/mentorList/command/MentorList.java
  gomen/src/main/java/com/tuna/gomen/mentorList/command/MentorListRepository.java
  gomen/src/main/java/com/tuna/gomen/mentorList/command/dummy.java
  gomen/src/main/java/com/tuna/gomen/mentorList/dummy.java
  gomen/src/main/java/com/tuna/gomen/mentorList/query/controller/MentorListController.java
  gomen/src/main/java/com/tuna/gomen/mentorList/query/domain/entity/MentorList.java
  gomen/src/main/java/com/tuna/gomen/mentorList/query/dto/MentorListDTO.java
  gomen/src/main/java/com/tuna/gomen/mentorList/query/service/MentorListService.java
  gomen/src/main/java/com/tuna/gomen/mentorList/query/service/MentorListServiceImpl.java
  gomen/src/main/java/com/tuna/gomen/mentoring/MentoringService.java
  gomen/src/main/java/com/tuna/gomen/mentoring/command/Mentoring.java
  gomen/src/main/java/com/tuna/gomen/mentoring/command/MentoringAcceptRequest.java
  gomen/src/main/java/com/tuna/gomen/mentoring/command/MentoringController.java
  gomen/src/main/java/com/tuna/gomen/mentoring/command/MentoringRepository.java
  gomen/src/main/java/com/tuna/gomen/mentoring/command/MentoringRequest.java
  gomen/src/main/java/com/tuna/gomen/mentoring/command/MentoringRequestPK.java
  gomen/src/main/java/com/tuna/gomen/mentoring/command/MentoringService.java
  gomen/src/main/java/com/tuna/gomen/mentoringBoard/command/dummy.java
  gomen/src/main/java/com/tuna/gomen/mentoringBoard/dummy.java
  gomen/src/main/java/com/tuna/gomen/mentoringBoard/query/controller/MentoringBoardController.java
  gomen/src/main/java/com/tuna/gomen/mentoringBoard/query/domain/entity/MentoringBoard.java
  gomen/src/main/java/com/tuna/gomen/mentoringBoard/query/dto/MentoringBoardDTO.java
  gomen/src/main/java/com/tuna/gomen/mentoringBoard/query/service/MentoringBoardService.java
  gomen/src/main/java/com/tuna/gomen/mentoringBoard/query/service/MentoringBoardServiceImpl.java
  gomen/src/main/java/com/tuna/gomen/mentoringspace/command/MentoringSpace.java
  gomen/src/main/java/com/tuna/gomen/mentoringspace/command/MentoringSpaceController.java
  gomen/src/main/java/com/tuna/gomen/mentoringspace/command/MentoringSpaceRepository.java
  gomen/src/main/java/com/tuna/gomen/mentoringspace/command/MentoringSpaceService.java
  gomen/src/main/java/com/tuna/gomen/mentoringspace/dummy.java
  gomen/src/main/resources/mapper/MentorListMapper.xml
  gomen/src/main/resources/mapper/MentoringBoardMapper.xml
  gomen/src/main/resources/mapper/MentoringMapper.xml
Labels: 🐣enhancement

#50 Feature/bookmarkinsert
  .idea/dataSources.xml
  gomen/src/main/java/com/tuna/gomen/GomenApplication.java
  gomen/src/main/java/com/tuna/gomen/board/command/entity/Board.java
  gomen/src/main/java/com/tuna/gomen/board/repository/BoardRepository.java
  gomen/src/main/java/com/tuna/gomen/bookMarkandLike/controller/BookmarkController.java
  gomen/src/main/java/com/tuna/gomen/bookMarkandLike/domain/entity/BookmarkEntity.java
  gomen/src/main/java/com/tuna/gomen/bookMarkandLike/dto/BookmarkDTO.java
  gomen/src/main/java/com/tuna/gomen/bookMarkandLike/dto/BookmarkedBoardDto.java
  gomen/src/main/java/com/tuna/gomen/bookMarkandLike/dummy.java
  gomen/src/main/java/com/tuna/gomen/bookMarkandLike/entity/Bookmark.java
  gomen/src/main/java/com/tuna/gomen/bookMarkandLike/entity/BookmarkEntity.java
  gomen/src/main/java/com/tuna/gomen/bookMarkandLike/entity/BookmarkId.java
  gomen/src/main/java/com/tuna/gomen/bookMarkandLike/repository/BookmarkRepository.java
  gomen/src/main/java/com/tuna/gomen/bookMarkandLike/service/BookmarkService.java
  gomen/src/main/java/com/tuna/gomen/bookMarkandLike/service/BookmarkService2.java
  gomen/src/main/java/com/tuna/gomen/mapper/BookmarkMapper.java
  gomen/src/main/java/com/tuna/gomen/user/command/entity/User.java
  gomen/src/main/java/com/tuna/gomen/user/repository/UserRepository.java
  gomen/src/main/resources/application.yml
Labels: 🐣enhancement

#54 Update DummyData_New.sql
  DummyData_New.sql
Labels: Database-fix

#55 recruitboard조회 전체 수정
  gomen/src/main/java/com/tuna/gomen/mapper/TeamRecruitBoardMapper.java
  gomen/src/main/java/com/tuna/gomen/teamRecruitBoard/controller/TeamRecruitBoardController.java
  gomen/src/main/java/com/tuna/gomen/teamRecruitBoard/dto/TeamRecruitWithApplicantsDTO.java
  gomen/src/main/java/com/tuna/gomen/teamRecruitBoard/dummy.java
  gomen/src/main/java/com/tuna/gomen/teamRecruitBoard/service/TeamRecruitBoardService.java
  gomen/src/main/resources/mapper/TeamRecruitMapper.xml
Labels: 🐣enhancement

#58 Feature/report
  .idea/.name
  .idea/dataSources.xml
  gomen/src/main/java/com/tuna/gomen/board/entity/Board.java
  gomen/src/main/java/com/tuna/gomen/board/repository/BoardRepository.java
  gomen/src/main/java/com/tuna/gomen/comment/entity/Comment.java
  gomen/src/main/java/com/tuna/gomen/comment/repository/CommentRepository.java
  gomen/src/main/java/com/tuna/gomen/mapper/ReportMapper.java
  gomen/src/main/java/com/tuna/gomen/report/jpa/controller/ReportController.java
  gomen/src/main/java/com/tuna/gomen/report/jpa/dto/ReportDto.java
  gomen/src/main/java/com/tuna/gomen/report/jpa/entity/Report.java
  gomen/src/main/java/com/tuna/gomen/report/jpa/entity/ReportCategory.java
  gomen/src/main/java/com/tuna/gomen/report/jpa/repository/ReportCategoryRepository.java
  gomen/src/main/java/com/tuna/gomen/report/jpa/repository/ReportRepository.java
  gomen/src/main/java/com/tuna/gomen/report/jpa/service/ReportService.java
  gomen/src/main/java/com/tuna/gomen/report/mybatis/controller/ReportController.java
  gomen/src/main/java/com/tuna/gomen/report/mybatis/model/Report.java
  gomen/src/main/java/com/tuna/gomen/report/mybatis/service/ReportService.java
  gomen/src/main/java/com/tuna/gomen/report/postman
  gomen/src/main/java/com/tuna/gomen/user/command/entity/User.java
  gomen/src/main/java/com/tuna/gomen/user/repository/UserRepository.java
  gomen/src/main/resources/application.yml
  gomen/src/main/resources/mapper/ReportMapper.xml
Labels: 🐣enhancement

#60 게시글 생성, 삭제 기능 구현
  gomen/src/main/java/com/tuna/gomen/applicant/controller/ApplicantController.java
  gomen/src/main/java/com/tuna/gomen/applicant/dto/ApplicantDTO.java
  gomen/src/main/java/com/tuna/gomen/applicant/entity/Applicant.java
  gomen/src/main/java/com/tuna/gomen/applicant/entity/ApplicantId.java
  gomen/src/main/java/com/tuna/gomen/applicant/repository/ApplicantRepository.java
  gomen/src/main/java/com/tuna/gomen/applicant/service/ApplicantService.java
  gomen/src/main/java/com/tuna/gomen/applicant/service/ApplicantServiceImpl.java
  gomen/src/main/java/com/tuna/gomen/mapper/ApplicantMapper.java
  gomen/src/main/java/com/tuna/gomen/teamRecruitBoard/controller/TeamRecruitBoardController.java
  gomen/src/main/java/com/tuna/gomen/teamRecruitBoard/dto/TeamRecruitWithApplicantsDTO.java
  gomen/src/main/java/com/tuna/gomen/teamRecruitBoard/entity/TeamRecruitBoard.java
  gomen/src/main/java/com/tuna/gomen/teamRecruitBoard/repository/TeamRecruitBoardRepository.java
  gomen/src/main/java/com/tuna/gomen/teamRecruitBoard/service/TeamRecruitBoardServiceImpl.java
  gomen/src/main/java/com/tuna/gomen/teamRecruitBoard/service/TeamRecruitBoardServiceInterface.java
  gomen/src/main/resources/mapper/ApplicantMapper.xml
Labels: 🐣enhancement

#63 팀 신청, 삭제, 처리 기능 구현
  gomen/.DS_Store
  gomen/src/main/java/com/tuna/gomen/applicant/controller/ApplicantController.java
  gomen/src/main/java/com/tuna/gomen/applicant/entity/Applicant.java
  gomen/src/main/java/com/tuna/gomen/applicant/repository/ApplicantRepository.java
  gomen/src/main/java/com/tuna/gomen/applicant/service/ApplicantService.java
  gomen/src/main/java/com/tuna/gomen/applicant/service/ApplicantServiceImpl.java
  gomen/src/main/java/com/tuna/gomen/teamRecruitBoard/repository/TeamRecruitBoardRepository.java
Labels: 🐣enhancement

#64 Feature/mentoring
  .idea/dataSources.xml
  gomen/.DS_Store
  gomen/src/main/java/com/tuna/gomen/mapper/MentoringBoardMapper.java
  gomen/src/main/java/com/tuna/gomen/mentorList/command/MentorList.java
  gomen/src/main/java/com/tuna/gomen/mentorList/command/MentorListRepository.java
  gomen/src/main/java/com/tuna/gomen/mentorList/command/controller/MentorListCommandController.java
  gomen/src/main/java/com/tuna/gomen/mentorList/command/dto/MentorListRequest.java
  gomen/src/main/java/com/tuna/gomen/mentorList/command/dto/MentorListResponse.java
  gomen/src/main/java/com/tuna/gomen/mentorList/command/dummy.java
  gomen/src/main/java/com/tuna/gomen/mentorList/command/entity/MentorList.java
  gomen/src/main/java/com/tuna/gomen/mentorList/command/repository/MentorListRepository.java
  gomen/src/main/java/com/tuna/gomen/mentorList/command/service/MentorListService.java
  gomen/src/main/java/com/tuna/gomen/mentoring/command/MentoringRepository.java
  gomen/src/main/java/com/tuna/gomen/mentoring/command/controller/MentoringController.java
  gomen/src/main/java/com/tuna/gomen/mentoring/command/dto/MentoringAcceptRequest.java
  gomen/src/main/java/com/tuna/gomen/mentoring/command/dto/MentoringRequest.java
  gomen/src/main/java/com/tuna/gomen/mentoring/command/entity/Mentoring.java
  gomen/src/main/java/com/tuna/gomen/mentoring/command/entity/MentoringRequestPK.java
  gomen/src/main/java/com/tuna/gomen/mentoring/command/repository/MentoringRepository.java
  gomen/src/main/java/com/tuna/gomen/mentoring/command/service/MentoringService.java
  gomen/src/main/java/com/tuna/gomen/mentoringBoard/command/controller/AnswerController.java
  gomen/src/main/java/com/tuna/gomen/mentoringBoard/command/controller/QuestionController.java
  gomen/src/main/java/com/tuna/gomen/mentoringBoard/command/dto/AnswerRequest.java
  gomen/src/main/java/com/tuna/gomen/mentoringBoard/command/dto/AnswerResponse.java
  gomen/src/main/java/com/tuna/gomen/mentoringBoard/command/dto/AnswerUpdateRequest.java
  gomen/src/main/java/com/tuna/gomen/mentoringBoard/command/dto/QuestionRequest.java
  gomen/src/main/java/com/tuna/gomen/mentoringBoard/command/dto/QuestionResponse.java
  gomen/src/main/java/com/tuna/gomen/mentoringBoard/command/dto/QuestionUpdateRequest.java
  gomen/src/main/java/com/tuna/gomen/mentoringBoard/command/dummy.java
  gomen/src/main/java/com/tuna/gomen/mentoringBoard/command/enriry/Question.java
  gomen/src/main/java/com/tuna/gomen/mentoringBoard/command/entity/Answer.java
  gomen/src/main/java/com/tuna/gomen/mentoringBoard/command/entity/Question.java
  gomen/src/main/java/com/tuna/gomen/mentoringBoard/command/repository/AnswerRepository.java
  gomen/src/main/java/com/tuna/gomen/mentoringBoard/command/repository/QuestionRepository.java
  gomen/src/main/java/com/tuna/gomen/mentoringBoard/command/service/AnswerService.java
  gomen/src/main/java/com/tuna/gomen/mentoringBoard/command/service/QuestionService.java
  gomen/src/main/java/com/tuna/gomen/mentoringspace/command/MentoringSpace.java
  gomen/src/main/java/com/tuna/gomen/mentoringspace/command/MentoringSpaceController.java
  gomen/src/main/java/com/tuna/gomen/mentoringspace/command/MentoringSpaceRepository.java
  gomen/src/main/java/com/tuna/gomen/mentoringspace/command/MentoringSpaceService.java
  gomen/src/main/java/com/tuna/gomen/mentoringspace/command/controller/MentoringSpaceController.java
  gomen/src/main/java/com/tuna/gomen/mentoringspace/command/controller/MentoringSpaceMemberController.java
  gomen/src/main/java/com/tuna/gomen/mentoringspace/command/dto/MentoringSpaceMemberRequest.java
  gomen/src/main/java/com/tuna/gomen/mentoringspace/command/dto/MentoringSpaceMemberResponse.java
  gomen/src/main/java/com/tuna/gomen/mentoringspace/command/dto/PersonalInformationUpdateRequest.java
  gomen/src/main/java/com/tuna/gomen/mentoringspace/command/entity/MentoringSpace.java
  gomen/src/main/java/com/tuna/gomen/mentoringspace/command/entity/MentoringSpaceMember.java
  gomen/src/main/java/com/tuna/gomen/mentoringspace/command/entity/MentoringSpaceMemberPK.java
  gomen/src/main/java/com/tuna/gomen/mentoringspace/command/repository/MentoringSpaceMemberRepository.java
  gomen/src/main/java/com/tuna/gomen/mentoringspace/command/repository/MentoringSpaceRepository.java
  gomen/src/main/java/com/tuna/gomen/mentoringspace/command/service/MentoringSpaceMemberService.java
  gomen/src/main/java/com/tuna/gomen/mentoringspace/command/service/MentoringSpaceService.java
  gomen/src/main/java/com/tuna/gomen/mentoringspace/dummy.java
  gomen/src/main/java/com/tuna/gomen/user/command/entity/User.java
Labels: 🐣enhancement

#67 comment 기능 구현 완료
  gomen/src/main/java/com/tuna/gomen/comment/.DS_Store
  gomen/src/main/java/com/tuna/gomen/comment/controller/CommentController.java
  gomen/src/main/java/com/tuna/gomen/comment/dto/CommentDTO.java
  gomen/src/main/java/com/tuna/gomen/comment/entity/Comment.java
  gomen/src/main/java/com/tuna/gomen/comment/repository/CommentRepository.java
  gomen/src/main/java/com/tuna/gomen/comment/service/CommentService.java
Labels: 🐣enhancement

#66 Report 관련 Mybatis(controller에 주소)/JPA(postman 파일에 주소) 구현
  gomen/src/main/java/com/tuna/gomen/mapper/MentorListMapper.java
  gomen/src/main/java/com/tuna/gomen/mapper/ReportMapper.java
  gomen/src/main/java/com/tuna/gomen/report/mybatis/controller/ReportController.java
  gomen/src/main/java/com/tuna/gomen/report/mybatis/service/ReportService.java
  gomen/src/main/java/com/tuna/gomen/report/postman
  gomen/src/main/resources/mapper/ReportMapper.xml
Labels: 🐣enhancement

#68 feature/mail 쪽지 기능 구현
  gomen/src/main/java/com/tuna/gomen/mail/Mail.java
  gomen/src/main/java/com/tuna/gomen/mail/MailController.java
  gomen/src/main/java/com/tuna/gomen/mail/MailRepository.java
  gomen/src/main/java/com/tuna/gomen/mail/MailService.java
  gomen/src/main/java/com/tuna/gomen/mail/dummy.java
  gomen/src/main/java/com/tuna/gomen/mail/postman
  gomen/src/main/java/com/tuna/gomen/mapper/MailMapper.java
  gomen/src/main/resources/mapper/MailMapper.xml
Labels: 🐣enhancement

#70 칭호 생성 및 수정 및 조회, mail postman file에 주석 추가
  gomen/src/main/java/com/tuna/gomen/mail/postman
  gomen/src/main/java/com/tuna/gomen/title/controller/TitleController.java
  gomen/src/main/java/com/tuna/gomen/title/dummy.java
  gomen/src/main/java/com/tuna/gomen/title/entity/Title.java
  gomen/src/main/java/com/tuna/gomen/title/entity/TitleList.java
  gomen/src/main/java/com/tuna/gomen/title/entity/TitleListId.java
  gomen/src/main/java/com/tuna/gomen/title/repository/TitleListRepository.java
  gomen/src/main/java/com/tuna/gomen/title/repository/TitleRepository.java
  gomen/src/main/java/com/tuna/gomen/title/service/TitleService.java
  gomen/src/main/java/com/tuna/gomen/title/service/TitleServiceImpl.java
Labels: 🐣enhancement

#71 칭호 부여 기능 구현 완료
  gomen/src/main/java/com/tuna/gomen/title/controller/TitleListController.java
  gomen/src/main/java/com/tuna/gomen/title/entity/TitleList.java
  gomen/src/main/java/com/tuna/gomen/title/entity/TitleListId.java
  gomen/src/main/java/com/tuna/gomen/title/repository/TitleListRepository.java
  gomen/src/main/java/com/tuna/gomen/title/service/TitleListService.java
  gomen/src/main/java/com/tuna/gomen/title/service/TitleListServiceImpl.java
Labels: 🐣enhancement

#72 Feature/boardfix
  gomen/src/main/java/com/tuna/gomen/board/command/service/BoardService2.java
  gomen/src/main/java/com/tuna/gomen/board/query/controller/BoardController.java
  gomen/src/main/java/com/tuna/gomen/file/Service/FileStorageService.java
Labels: bug

#75 회원 신고시 벌점은 이미 구현 완료
  gomen/src/main/java/com/tuna/gomen/board/command/entity/Board.java
  gomen/src/main/java/com/tuna/gomen/comment/entity/Comment.java
  gomen/src/main/java/com/tuna/gomen/report/jpa/service/ReportService.java
  gomen/src/main/java/com/tuna/gomen/report/postman
Labels: 🐣enhancement

#76 commit
  gomen/src/main/java/com/tuna/gomen/file/Service/FileStorageService.java
Labels: bug

#79 Feature/mentoring
  gomen/src/main/java/com/tuna/gomen/file/Service/FileStorageService.java
  gomen/src/main/java/com/tuna/gomen/file/entity/MentoringFile.java
  gomen/src/main/java/com/tuna/gomen/file/repository/MentoringFileRepository.java
  gomen/src/main/java/com/tuna/gomen/mentoringBoard/command/controller/AnswerController.java
  gomen/src/main/java/com/tuna/gomen/mentoringBoard/command/controller/QuestionController.java
  gomen/src/main/java/com/tuna/gomen/mentoringBoard/command/dto/AnswerRequest.java
  gomen/src/main/java/com/tuna/gomen/mentoringBoard/command/dto/AnswerResponse.java
  gomen/src/main/java/com/tuna/gomen/mentoringBoard/command/dto/QuestionRequest.java
  gomen/src/main/java/com/tuna/gomen/mentoringBoard/command/dto/QuestionResponse.java
  gomen/src/main/java/com/tuna/gomen/mentoringBoard/command/entity/Answer.java
  gomen/src/main/java/com/tuna/gomen/mentoringBoard/command/entity/Question.java
  gomen/src/main/java/com/tuna/gomen/mentoringBoard/command/service/AnswerService.java
  gomen/src/main/java/com/tuna/gomen/mentoringBoard/command/service/QuestionService.java
  gomen/src/main/java/com/tuna/gomen/mentoringspace/command/controller/MentoringSpaceController.java
  gomen/src/main/java/com/tuna/gomen/mentoringspace/command/entity/MentoringSpace.java
  gomen/src/main/java/com/tuna/gomen/mentoringspace/command/repository/MentoringSpaceMemberRepository.java
  gomen/src/main/java/com/tuna/gomen/mentoringspace/command/service/MentoringSpaceService.java
Labels: 🐣enhancement

#82 Feature/title
  .gitignore
  .idea/.gitignore
  gomen/.gitignore
  gomen/src/main/java/com/tuna/gomen/.DS_Store
  gomen/src/main/java/com/tuna/gomen/comment/.DS_Store
  gomen/src/test/java/com/tuna/gomen/report/jpa/service/ReportServiceTest.java
Labels: bug

#89 starPointReview.xml 쿼리 작성
  gomen/src/main/java/com/tuna/gomen/mapper/StarPointReviewMapper.java
  gomen/src/main/resources/mapper/starPointReview.xml
Labels: 🐣enhancement

#93 회원 멘토여부 변경 기능 추가
  userservice/src/main/java/com/tuna/userservice/security/WebSecurity.java
  userservice/src/main/java/com/tuna/userservice/user/controller/UserController.java
  userservice/src/main/java/com/tuna/userservice/user/dto/UserDTO.java
  userservice/src/main/java/com/tuna/userservice/user/service/UserService.java
Labels: 🐣enhancement
